name: Push to Github CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: plant a tree in the garden
        run: node index.js > GARDEN.md
      - name: Commit change & Push
        run: |
          git config user.name 'amirisback'
          git config user.email 'amirisback.dev@gmail.com'
          git commit -am "upload artifact to github"
          git push